# Generated by Django 3.2.8 on 2021-10-06 08:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('Text', wagtail.core.blocks.RichTextBlock()), ('Image', wagtail.images.blocks.ImageChooserBlock()), ('Embeded', wagtail.embeds.blocks.EmbedBlock())], blank=True)),
            ],
            options={
                'verbose_name': 'Blog page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
