# Generated by Django 3.2.8 on 2021-10-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211006_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
