# Generated by Django 3.2.8 on 2021-10-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0008_alter_taggedblog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedblog',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedblog',
            name='tag',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
        migrations.DeleteModel(
            name='TaggedBlog',
        ),
    ]
